# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoices.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('address', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='person', chained_model_field='person', null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Address', verbose_name='address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'estimate',
                'verbose_name_plural': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='unit price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.Estimate', verbose_name='estimate')),
            ],
            options={
                'verbose_name': 'estimate line',
                'verbose_name_plural': 'estimate lines',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('number', models.IntegerField(unique=True, verbose_name='number')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('address', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='person', chained_model_field='person', null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Address', verbose_name='address')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Estimate', verbose_name='estimate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='unit price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.Invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='percent')),
            ],
            options={
                'verbose_name': 'VAT',
                'verbose_name_plural': 'VATs',
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat',
            field=models.ForeignKey(default=invoices.models.default_vat, on_delete=django.db.models.deletion.CASCADE, to='invoices.VAT', verbose_name='vat'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='vat',
            field=models.ForeignKey(default=invoices.models.default_vat, on_delete=django.db.models.deletion.CASCADE, to='invoices.VAT', verbose_name='vat'),
        ),
    ]
