# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('gid', models.CharField(max_length=10, unique=True, verbose_name='guifi id')),
                ('mainipv4', models.CharField(max_length=20, verbose_name='main IPv4')),
                ('status', models.CharField(choices=[(b'Planned', b'Planned'), (b'Working', b'Working'), (b'Testing', b'Testing'), (b'Building', b'Building'), (b'Reserved', b'Reserved'), (b'Dropped', b'Dropped')], max_length=30, verbose_name='status')),
                ('firmware', models.CharField(max_length=100, verbose_name='firmware')),
                ('device_type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'device',
                'verbose_name_plural': 'device',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('gid', models.CharField(max_length=10, unique=True, verbose_name='guifi id')),
                ('status', models.CharField(choices=[(b'Planned', b'Planned'), (b'Working', b'Working'), (b'Testing', b'Testing'), (b'Building', b'Building'), (b'Reserved', b'Reserved'), (b'Dropped', b'Dropped')], max_length=30, verbose_name='status')),
                ('latitude', models.CharField(max_length=50, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='longitude')),
                ('antenna_elevation', models.IntegerField(verbose_name='antenna elevation')),
                ('sync_with_guifinet', models.BooleanField(default=False, help_text='When this checkbox is active changes will be commited to guifi.net.', verbose_name='Sync with guifi.net')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Member', verbose_name='owner')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('gid', models.CharField(max_length=10, unique=True, verbose_name='guifi id')),
                ('parent_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guifi.Zone')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guifi.Zone', verbose_name='zone'),
        ),
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guifi.Node', verbose_name='node'),
        ),
    ]
