# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'quota',
                'verbose_name_plural': 'quotas',
            },
        ),
        migrations.CreateModel(
            name='QuotaInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='invoice')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.Quota', verbose_name='quota type')),
            ],
            options={
                'verbose_name': 'quota invoice',
                'verbose_name_plural': 'quota invoices',
            },
        ),
        migrations.CreateModel(
            name='QuotaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'anual'), (2, 'monthly')], verbose_name='periodicity')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='quantity')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'quota type',
                'verbose_name_plural': 'quota types',
            },
        ),
        migrations.AddField(
            model_name='quota',
            name='quota_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.QuotaType', verbose_name='quota type'),
        ),
    ]
