# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('gid', models.CharField(max_length=10, unique=True, verbose_name='guifi id')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('fid', models.CharField(max_length=15, verbose_name='nif/ifz')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Person', verbose_name='person'),
        ),
    ]
